node('root') {
def buildWorld

stage('Checkout') {
    checkout([$class: 'GitSCM',
        branches: [[name: '*/main']],
        extensions: [[$class: 'CloneOption', timeout: 120]],
        gitTool: 'Default', 
        userRemoteConfigs: [[url: 'https://git.freebsd.org/src.git']]
    ])

//    git branch: 'main', url: 'https://git.freebsd.org/src.git'

    dir('a-child-repo') {
       git branch: 'main', url: 'https://github.com/ronaldklop/ci.git'
    }

//    env.JAVA_HOME="${tool 'JDK8'}"
//    env.PATH="${env.JAVA_HOME}/bin:${env.PATH}" // set java home in jdk environment
//    gradleHome = tool '3.4.1' 
}

stage('Build') {
  if (isUnix()) {
     sh "'freebsd/build/worls/build.sh'"
  } else {
     bat(/"${gradleHome}\bin\gradle" clean build/)
  }
}
}
